// <auto-generated />
namespace MonoTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class RenameMakeIdToVehicleMakeId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameMakeIdToVehicleMakeId));
        
        string IMigrationMetadata.Id
        {
            get { return "202508181440391_RenameMakeIdToVehicleMakeId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
